/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: dPWt/xLFlxUnpikJcEe2pN/GJ9Y74vzrCIzyww4v6nOH5FwEfoLjmMH1r73I+XjMiyJSbprYOYlGf4/YhAkK0g==
 */

/* eslint-disable */
// tslint:disable

import Links, {Links_InsertParameters} from './links'
import Users, {Users_InsertParameters} from './users'

interface DatabaseSchema {
  links: {record: Links, insert: Links_InsertParameters};
  users: {record: Users, insert: Users_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  Links,
  Links_InsertParameters,
  Users,
  Users_InsertParameters,
}
