/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: RsWOPU6S8J0j+7UOkaNNBIw/7MpswPpKuO+mwFY2out5WW2nlS3yYPu71gk+45nDIOGf5Iz2bWtAbvVM14XBfg==
 */

/* eslint-disable */
// tslint:disable

interface Links {
  key: string & {readonly __brand?: 'links_key'}
  /**
   * @default 0
   */
  num_visits: (number) | null
  original_url: string
  owner: (string) | null
}
export default Links;

interface Links_InsertParameters {
  key: string & {readonly __brand?: 'links_key'}
  /**
   * @default 0
   */
  num_visits?: (number) | null
  original_url: string
  owner?: (string) | null
}
export type {Links_InsertParameters}
