/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: wc2qiheoYxxs/Ll5iYhRHDC9JmAlaZjn1R9z4UKHbBEadlhJKXTOoE/veaZQaMJFAHkoG71TtkpTiacikxYGJQ==
 */

/* eslint-disable */
// tslint:disable

interface Links {
  original_link: (string) | null
  shortened_link: (string) | null
}
export default Links;

interface Links_InsertParameters {
  original_link?: (string) | null
  shortened_link?: (string) | null
}
export type {Links_InsertParameters}
